# Alacritty keymaps
# Leaving `bindings` empty preserves the built-in defaults for your platform.
# To customize or override, uncomment entries you want.
# To remove a default binding, you can set its action to "ReceiveChar" (let the app receive the key)
# or "None" (do nothing).

[keyboard]
bindings = [
  # ----- Common examples (uncomment to use) -----

  # Copy / Paste
  # Linux/BSD/Windows style:
  # { key = "C", mods = "Control|Shift", action = "Copy" },
  # { key = "V", mods = "Control|Shift", action = "Paste" },

  # macOS style:
  { key = "C", mods = "Command", action = "Copy" },
  { key = "V", mods = "Command", action = "Paste" },

  # Font size controls
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "NumpadAdd", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "NumpadSubtract", mods = "Control", action = "DecreaseFontSize" },
  { key = "Zero", mods = "Control", action = "ResetFontSize" },

  # New window
  # { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },   # Linux/BSD/Windows
  # { key = "N", mods = "Command", action = "CreateNewWindow" },         # macOS

  # Fullscreen toggle
  # { key = "F11", action = "ToggleFullscreen" },
  # macOS alternative:
  # { key = "Enter", mods = "Command|Control", action = "ToggleSimpleFullscreen" },

  # Scrolling
  # { key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
  # { key = "PageDown", mods = "Shift", action = "ScrollPageDown" },
  # { key = "Home", mods = "Shift", action = "ScrollToTop" },
  # { key = "End", mods = "Shift", action = "ScrollToBottom" },

  # Search (buffer)
  # { key = "F", mods = "Control|Shift", action = "SearchForward" },
  # { key = "B", mods = "Control|Shift", action = "SearchBackward" },

  # Vi mode (navigation)
  # { key = "V", mods = "Control|Shift", action = "ToggleViMode" },

  # Clear selection
  # { key = "Escape", action = "ClearSelection" },

  # Spawn new instance (another terminal window)
  # { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },

  # Quit
  # { key = "Q", mods = "Control|Shift", action = "Quit" },

  # ----- Example of removing an inherited default binding -----
  # This would make Ctrl+Shift+C do nothing (instead of Copy):
  # { key = "C", mods = "Control|Shift", action = "None" },

  # Or let the underlying app receive the keypress:
  # { key = "C", mods = "Control|Shift", action = "ReceiveChar" },
]
