[font]
size = 12.0

[font.bold]
family = "0xProto Nerd Font"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font"
style = "Italic"

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[window]
title = "Alacritty"
decorations = "none"
dynamic_title = false

[colors.selection]
text = "#1D2021"
background = "#A89984"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
